import type React from "react"
import type { Metadata, Viewport } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { NotificationProvider } from "@/contexts/notification-context"
// Utiliser le MainLayout local
import { MainLayout } from "@/components/layout/main-layout"
// Importer le AuthProvider
import { AuthProvider } from "@/contexts/auth-context"
// Import the LoolyyBWidget component
import { LoolyyBWidget } from "@/components/loolyyb-widget"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"), // Ajoutez votre URL de production ici à terme
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  themeColor: "black", // Ou la couleur que vous aviez définie
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${inter.className} bg-gradient-to-br from-[#1a0d2e] to-[#3d1155]`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} disableTransitionOnChange>
          <AuthProvider>
            <NotificationProvider>
              <MainLayout>{children}</MainLayout>
              <LoolyyBWidget />
            </NotificationProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
